# Generated by Django 5.0.5 on 2024-09-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('valor', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('salarioBase', models.CharField(max_length=20)),
                ('nivel', models.CharField(max_length=20)),
                ('beneficio', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Folha_de_pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valorLiquido', models.FloatField(max_length=8)),
                ('valorBruto', models.FloatField(max_length=8)),
                ('horaExtra', models.FloatField(max_length=6)),
                ('horasTrabalhadas', models.FloatField(max_length=4)),
                ('adicionalNoturno', models.FloatField(max_length=4)),
                ('adicionalInsalubridade', models.FloatField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('salarioBase', models.FloatField(max_length=8)),
                ('nivel', models.IntegerField(max_length=1)),
            ],
        ),
    ]
